if(EXISTS "C:/Users/User/Desktop/c++/ITMO/BaseOfProgramming/labwork-6-N4R1CK/tests/parser_tests[1]_tests.cmake")
  include("C:/Users/User/Desktop/c++/ITMO/BaseOfProgramming/labwork-6-N4R1CK/tests/parser_tests[1]_tests.cmake")
else()
  add_test(parser_tests_NOT_BUILT parser_tests_NOT_BUILT)
endif()
